name: Node.js CI
on: [push]
jobs:
  test-against-examples:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
